[features]
seeds = false
skip-lint = false

[test.validator]
url = "https://api.devnet.solana.com"

# pyth_account
[[test.validator.clone]]
address = "J83w4HKfqxwcq3BEMMkPFSppX3gqekLyLJBexebFVkix"



[programs.localnet]
raffle = "3MUA6ysVh3RdBtRVU26ME2W5NfTW9PcxdnhWzAVHn91Z"

[programs.devnet]
raffle = "3MUA6ysVh3RdBtRVU26ME2W5NfTW9PcxdnhWzAVHn91Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
